### ISSUE TITLE
Test failures due to dockerode regression in buildImage()

### ISSUE THREAD

**Issue by kb2ma** [balena-io-modules/balena-compose#15]
Tests fail with a timeout. Root cause is regression in dockerode v3.3.4 that hangs balena-compose use of its `buildImage()` function. See [Issue](https://github.com/apocas/dockerode/issues/696) on that repo for details. We are awaiting response to a [fix PR](https://github.com/apocas/dockerode/pull/695).

```
  136 passing (8m)
  2 pending
  14 failing

  1) Directory build
       should build a directory image:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/kbee/dev/balena-compose/repo/test/build/all.spec.ts)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
...
```

**Comment by kb2ma** [comment]
As a workaround for tests to pass, pinned dockerode to v3.3.3 in #11.

**Comment by kb2ma** [comment]
Closing since the immediate issue is worked around. Created #17 to track pinning on dockerode v3.3.3.
